### ISSUE TITLE
Change this repo to installable WP plugin

### ISSUE THREAD

**Issue by primozcigler** [primozcigler/wordpress-one-click-demo-install#8]
The aim of this issue is to discuss the migration of this script to standalone WP plugin.

As [TGMPA v2.5.0+](https://github.com/TGMPA/TGM-Plugin-Activation/releases/tag/2.5.0) supports plugins to be downloaded directly from the github, it would make more sense to suggest the demo content installation plugin, instead of bundling the script with the theme.
### Pros
- more lightweight theme
- not everyone wants/needs demo content installation
- possible to deactivate and delete the plugin after the demo content has been imported (which makes sense, as demo content should be imported only once)
- this change (to plugin) may invite more WP developers to use and contribute to this repo
### Cons

_I cannot think of one really. Maybe that the user could overlook the option to install required/recommended plugins? But in this case, it will also experience the other problems as well. TGMPA is mature now and users are (based on the experience from support) familiar with the installation of required/recommended plugins right after the theme activation._

---

I'd like to invite @FrankM1, @capuderg and @Prelc to discuss the pros/cons and the roadmap how to get there. Also all the suggestions about the features and bug reports with the current script will be highly appreciated, so we implement/fix them along the way!

**Comment by FrankM1** [comment]
Hi,

Thanks for the invite.

I also believe making the library into a plugin is the logical step forward. There are almost no cons to that approach. I have already started the implementation as a plugin but I haven't completed it yet. I think I'll push it to github so you guys can take a look. 

One problem we need to solve is a simpler way to generate the files needed for import in one go instead of juggling 4 different plugins.

**Comment by capuderg** [comment]
I also like the idea of one click demo import plugin. As you both stated, there are no cons that I can think of. 

I especially love the separation of this functionality from the theme and that you can simply delete the plugin after the demo import. So, this is a great idea!

@FrankM1 you are suggesting that we add an export option to this plugin as well? We are currently generating the import data xml and the widgets json file on our server on a daily basis and we then pull these files directly from the server, so we don't include the import files in the theme anymore.

This is still a good idea for the future (export option), but I think we should focus on the import first.

**Comment by primozcigler** [comment]
@capuderg did exactly that https://github.com/proteusthemes/one-click-demo-import
